### ISSUE TITLE
i can't show my project spine（.atlas, .json, .png）

### ISSUE THREAD

**Issue by al1020119** [maxgribov/SpineSampleProject#3]
this is our project resource

.atlas, .json, .png

**Comment by maxgribov** [comment]
Here is docs: https://github.com/maxgribov/Spine/wiki/Assets

**Comment by al1020119** [comment]
Thank you. I understand what you mean. I've read the document, but our company's project is not separate about the picture except JSON file. 



It's in a Atlas set, one. PNG file and one. Atlas file, but your library restricts asset, so our project cannot be loaded. Because we are using swift, we have tried many related libraries which can not do better, or are too old, so we hope to get your guidance or help.

**Comment by al1020119** [comment]
This is My resource file

![snip20181225_39](https://user-images.githubusercontent.com/9606161/50410912-044eb000-0837-11e9-8f69-7c650840854a.png)

**Comment by maxgribov** [comment]
You don't need export atlas from Spine App, just export only json, and use the original images that you used in Spine App for animation. My library does not support Spine App atlases.

**Comment by maxgribov** [comment]
Just find the "images" folder in the project and select it... the properties will specify the path to this folder... there are your original images that you need to use:

<img width="527" alt="screenshot 2018-12-25 at 06 27 56" src="https://user-images.githubusercontent.com/6514571/50411115-9a221500-080e-11e9-9f53-a5c8aeee5f16.png">

**Comment by al1020119** [comment]
Ok,  I understand.
Thank you

but, can i make the scale and move animation?

**Comment by al1020119** [comment]
If your library can support Spine App atlases. 



I think it would be better, because many companies are considering using Spine App atlases, especially now that our spine App atlases are ready, it's also a project to use tools to turn into fragmented images.

**Comment by al1020119** [comment]
And spine app atlases，It is still widely used, especially in the game industry, or game APP.

Of course, that's just my personal advice.

Finally，Thank you for your guidance.

**Comment by maxgribov** [comment]
I don't plan work on the implementation of the Spine App atlases, sorry. But you free to do it yourself if you want.. This library is open source.

**Comment by maxgribov** [comment]
my library uses native SpriteKit atlases. The pictures you add are automatically grouped into atlases like the one you showed above.
