### ISSUE TITLE
SetAttachment!

### ISSUE THREAD

**Issue by zerogone01** [maxgribov/SpineSampleProject#4]
Hello! I appreciate it very much for your contribution! I read the documentation and i tried to implement some attachments but i can't find the code how to make this! Please, help me!

**Comment by maxgribov** [comment]
This should help:  https://github.com/maxgribov/Spine/wiki/Assets

**Comment by zerogone01** [comment]
I have running the animation on the app.. but I want to get a slot and set a new attachment . I looked documentation and appear Skeleton.skeleton.SetAttachment(name slot, name attachment) but this doesn't appear when I tried to invoke it from code. How can I do this?

**Comment by maxgribov** [comment]
Actually, direct management of attachments and slots is not part of the public api.. So if you need such functionality, you can implement it yourself in your fork. I had no plans to make such a public feature. Sorry.
