### ISSUE TITLE
support atlas (. png /. atlas / json)?

### ISSUE THREAD

**Issue by al1020119** [maxgribov/SpineSampleProject#5]
I found that we can only use texture atlas (. atlas) to export fragments again. Is there any way to use your spine to read and use them directly and display them (. png /. atlas / json)

like this

![spineboy](https://user-images.githubusercontent.com/9606161/53874756-0eaed680-403e-11e9-9f11-e11f6effd871.png)

![snip20190306_41](https://user-images.githubusercontent.com/9606161/53874798-238b6a00-403e-11e9-90b3-df360dbc6fbe.png)

Or, can you support this direct use?

**Comment by al1020119** [comment]
Or you have what good way?

I need your help, thank you

**Comment by al1020119** [comment]
Two problems encountered

1. We have an old Spring software, but when we export it, there are only atlases, no fragments.

2. Then we upgraded a new one. When we found the export, the inside was bones, but when I went back to your source file, the inside JSON was skeleton.

**Comment by maxgribov** [comment]
I don't use the Spine app to export images from there. I only export JSON with skeleton and animations. All images I have prepared separately. I don't see what the problem is to take these images and add them to Xcode.

**Comment by al1020119** [comment]
Yes, but the JSON I export is not Skeleton, it's like this.

{
"bones": [
	{ "name": "root" },
	{ "name": "hip", "parent": "root", "x": 0.64, "y": 114.41 }
],
"slots": [
	{ "name": "template", "bone": "root", "color": "ff898c86" }
],
"skins": {
	"default": {
		"eyes": {
			"eyes": { "x": 28.94, "y": -32.92, "rotation": -86.9, "width": 34, "height": 27 },
			"eyes-closed": { "x": 28.77, "y": -32.86, "rotation": -86.9, "width": 34, "height": 27 }
		},
		"torso": {
			"torso": { "x": 44.57, "y": -7.08, "rotation": -94.95, "width": 68, "height": 92 }
		}
	}
},
"animations": {
	"jump": {
		"bones": {
			"root": {
				"rotate": [
					{ "time": 0, "angle": 0 },
					{ "time": 0.4333, "angle": -14.52 },
					{ "time": 0.8, "angle": 9.86 },
					{ "time": 1.3666, "angle": 0 }
				],
				"scale": [
					{ "time": 0, "x": 1, "y": 1, "curve": "stepped" },
					{ "time": 1.3666, "x": 1, "y": 1 }
				]
			}
		}
	},
	"walk": {
		"bones": {
			"head": {
				"rotate": [
					{
						"time": 0,
						"angle": 3.6,
						"curve": [ 0, 0, 0.704, 1.61 ]
					},
					{ "time": 0.1666, "angle": -0.2 },
					{ "time": 0.2666, "angle": 6.1 },
					{ "time": 0.4, "angle": 3.45 },
					{
						"time": 0.5333,
						"angle": 5.17,
						"curve": [ 0, 0, 0.704, 1.61 ]
					},
					{ "time": 0.7, "angle": 1.1 },
					{ "time": 0.8, "angle": 6.09 },
					{ "time": 0.9333, "angle": 2.28 },
					{ "time": 1.0666, "angle": 3.6 }
				]
			}
		}
	}
}
}

So can`t show it!

**Comment by al1020119** [comment]
I found that it's far from your JSON format. I don't know if it's not in the right format or whether it's an export problem.

**Comment by maxgribov** [comment]
you should check Spine app documentation to understand how correctly export skeleton with animations into json.

**Comment by al1020119** [comment]
Okay, I'll try, but the end result of my discussion is that either we support texture atlas or we switch to other schemes.

Can you support texture atlas? Because we use texture atlas for Android and H5, they don't use fragments, so we need two sets of announcement resources to download. My guide disagrees with this scheme. In this case, I may need to use game engine to load keel animation.

Thanks！

**Comment by al1020119** [comment]
Moreover, we found that if we use this method, we can not download resources from the server, but can only pack into assets every time.

**Comment by maxgribov** [comment]
sorry, but I don't plan to add support for Spine app atlases. But since this is an open source library, you can always add your own functionality.

**Comment by zhangferry** [comment]
> I found that we can only use texture atlas (. atlas) to export fragments again. Is there any way to use your spine to read and use them directly and display them (. png /. atlas / json)
> 
> like this
> 
> ![spineboy](https://user-images.githubusercontent.com/9606161/53874756-0eaed680-403e-11e9-9f11-e11f6effd871.png)
> 
> ![snip20190306_41](https://user-images.githubusercontent.com/9606161/53874798-238b6a00-403e-11e9-90b3-df360dbc6fbe.png)
> 
> Or, can you support this direct use?

Did you find a solution?

**Comment by maxgribov** [comment]
sorry guys, my library doesn't support working with such atlases.  If you need it, you can write your own implementation. code is open.

**Comment by al1020119** [comment]
I've done it, or I can help you with byte parsing of large atlases and Altas files.

**Comment by al1020119** [comment]
> > I found that we can only use texture atlas (. atlas) to export fragments again. Is there any way to use your spine to read and use them directly and display them (. png /. atlas / json)
> > like this
> > ![spineboy](https://user-images.githubusercontent.com/9606161/53874756-0eaed680-403e-11e9-9f11-e11f6effd871.png)
> > ![snip20190306_41](https://user-images.githubusercontent.com/9606161/53874798-238b6a00-403e-11e9-90b3-df360dbc6fbe.png)
> > Or, can you support this direct use?
> 
> Did you find a solution?



I've done it, or I can help you with byte parsing of large atlases and Altas files.

**Comment by riyanpratamap** [comment]
> > > I found that we can only use texture atlas (. atlas) to export fragments again. Is there any way to use your spine to read and use them directly and display them (. png /. atlas / json)
> > > like this
> > > ![spineboy](https://user-images.githubusercontent.com/9606161/53874756-0eaed680-403e-11e9-9f11-e11f6effd871.png)
> > > ![snip20190306_41](https://user-images.githubusercontent.com/9606161/53874798-238b6a00-403e-11e9-90b3-df360dbc6fbe.png)
> > > Or, can you support this direct use?
> > 
> > 
> > Did you find a solution?
> 
> I've done it, or I can help you with byte parsing of large atlases and Altas files.

Is there any solution for that?

**Comment by al1020119** [comment]
> > > > I found that we can only use texture atlas (. atlas) to export fragments again. Is there any way to use your spine to read and use them directly and display them (. png /. atlas / json)
> > > > like this
> > > > ![spineboy](https://user-images.githubusercontent.com/9606161/53874756-0eaed680-403e-11e9-9f11-e11f6effd871.png)
> > > > ![snip20190306_41](https://user-images.githubusercontent.com/9606161/53874798-238b6a00-403e-11e9-90b3-df360dbc6fbe.png)
> > > > Or, can you support this direct use?
> > > 
> > > 
> > > Did you find a solution?
> > 
> > 
> > I've done it, or I can help you with byte parsing of large atlases and Altas files.
> 
> Is there any solution for that?

I found the answer from here.

http://zh.esotericsoftware.com/spine-runtimes

![图片](https://user-images.githubusercontent.com/9606161/58626789-309bba80-8308-11e9-8304-4de755f98eb1.png)
