### ISSUE TITLE
how to fix this bug

### ISSUE THREAD

**Issue by lexuanquynh** [maxgribov/SpineSampleProject#6]
<img width="876" alt="Screenshot 2023-03-29 at 11 07 07" src="https://user-images.githubusercontent.com/17588791/228424222-7ee49ab8-954c-486a-a5d1-4d3855e96cc7.png">

**Comment by maxgribov** [comment]
Just updated the Spine package with the fix. Try compile the SpineSampleProject and check if an error is gone.

**Comment by davidfuzju** [comment]
hi there, I clone the sample and Xcode still report this error, would you help me?
![image](https://github.com/maxgribov/SpineSampleProject/assets/3890843/13b137ce-747d-4117-969f-01cf995ddf80)

**Comment by maxgribov** [comment]
@SuperMarioBean  looks like you need update Spine package. Because code should looks like this:
<img width="1721" alt="Screenshot 2023-07-16 at 10 10 52" src="https://github.com/maxgribov/SpineSampleProject/assets/6514571/3c9134f2-1a2d-4cc7-9a5e-ac9044dd1bd5">

**Comment by davidfuzju** [comment]
> @SuperMarioBean looks like you need update Spine package. Because code should looks like this: <img alt="Screenshot 2023-07-16 at 10 10 52" width="1721" src="https://user-images.githubusercontent.com/6514571/253790106-3c9134f2-1a2d-4cc7-9a5e-ac9044dd1bd5.png">

thank your~
